import { createHash } from "node:crypto";
import { formatMoney } from "./fees";

/**
 * Contract templates rendered from structured terms. The rendered text and its SHA-256 are
 * frozen when the contract is sent; signatures bind to that hash, so any later edit voids them.
 * Templates are a starting point, not legal advice — the page says so.
 */

export type ContractTerms = {
  kind: "work_for_hire" | "revshare";
  projectName: string;
  clientName: string;
  makerName: string;
  roleTitle: string;
  scope: string;
  currency: string;
  milestones: { title: string; amountCents: number | null }[];
  revsharePercent: number | null;
  ipAssignment: "assign_on_payment" | "assign_on_signing" | "license";
  credit: string;
  portfolioRights: boolean;
  confidentiality: boolean;
};

const IP_TEXT: Record<ContractTerms["ipAssignment"], string> = {
  assign_on_payment:
    "Intellectual property in each deliverable is assigned to the Client when the milestone that covers it is paid. Until then it remains with the Maker.",
  assign_on_signing: "Intellectual property in all deliverables is assigned to the Client from creation.",
  license: "The Maker keeps ownership of the deliverables and grants the Client a perpetual, worldwide, non-exclusive licence to use them in the Project and its marketing.",
};

export function renderContract(t: ContractTerms): string {
  const lines = [
    `# ${t.kind === "revshare" ? "Revenue-share collaboration agreement" : "Work-for-hire agreement"}`,
    "",
    `**Project:** ${t.projectName}  `,
    `**Client:** ${t.clientName}  `,
    `**Maker:** ${t.makerName}  `,
    `**Role:** ${t.roleTitle}`,
    "",
    "## 1. Scope",
    t.scope.trim() || "As described in the milestones below.",
    "",
    "## 2. Milestones",
    ...t.milestones.map((m, i) => `${i + 1}. ${m.title}${m.amountCents != null ? ` — ${formatMoney(m.amountCents, t.currency)}` : ""}`),
    "",
  ];
  if (t.kind === "work_for_hire") {
    lines.push(
      "## 3. Payment",
      "The Client funds each milestone in advance through Guildhall. Funds are held until the Client approves the milestone's deliverables (for example by approving the linked asset review) and are then released to the Maker. Either party may open a dispute before release.",
      "",
    );
  } else {
    lines.push(
      "## 3. Revenue share",
      `The Maker receives ${t.revsharePercent ?? 0}% of the Project's net revenue, paid quarterly after launch, for as long as the Project earns revenue. No fees are due before launch.`,
      "",
    );
  }
  lines.push(
    "## 4. Intellectual property",
    IP_TEXT[t.ipAssignment],
    t.portfolioRights ? "The Maker may show the deliverables in their portfolio after the Project's public announcement." : "The Maker may not show the deliverables publicly without the Client's written consent.",
    "",
    "## 5. Credits",
    `The Maker will be credited as: "${t.credit}".`,
    "",
  );
  if (t.confidentiality) {
    lines.push("## 6. Confidentiality", "Both parties keep unannounced details of the Project confidential until the Client announces them publicly.", "");
  }
  lines.push(
    `## ${t.confidentiality ? 7 : 6}. Ending the agreement`,
    "Either party may end this agreement with 14 days' notice. Completed and funded milestones are paid; intellectual property follows section 4 for work already paid for.",
    "",
    "_Generated by Guildhall from a template. It is not legal advice; have it reviewed for your jurisdiction._",
  );
  return lines.join("\n");
}

export function contractHash(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}
