/** Shipped-credit helpers (C11). */

export const CREDIT_SOURCES = [
  { host: "store.steampowered.com", label: "Steam" },
  { host: "www.igdb.com", label: "IGDB" },
  { host: "igdb.com", label: "IGDB" },
  { host: "www.mobygames.com", label: "MobyGames" },
  { host: "mobygames.com", label: "MobyGames" },
  { host: "itch.io", label: "itch.io" },
  { host: "store.epicgames.com", label: "Epic" },
  { host: "www.gog.com", label: "GOG" },
  { host: "store.playstation.com", label: "PlayStation" },
  { host: "www.xbox.com", label: "Xbox" },
  { host: "www.nintendo.com", label: "Nintendo" },
  { host: "apps.apple.com", label: "App Store" },
  { host: "play.google.com", label: "Google Play" },
];

/** Normalise a game title so "Tidebound: Deluxe Edition" and "tidebound deluxe edition" match. */
export function titleKey(title: string): string {
  return title
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/** Accept only https links to known storefronts/databases, or any *.itch.io page. */
export function creditSource(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.protocol !== "https:") return null;
    if (u.hostname.endsWith(".itch.io")) return "itch.io";
    return CREDIT_SOURCES.find((s) => s.host === u.hostname)?.label ?? null;
  } catch {
    return null;
  }
}

export type CreditStatus = "verified" | "confirmed" | "self_reported";

export function creditStatus(source: "self" | "guildhall", confirmations: number): CreditStatus {
  if (source === "guildhall") return "verified";
  return confirmations > 0 ? "confirmed" : "self_reported";
}

export function creditsMarkdown(projectName: string, rows: { name: string; handle: string; role: string }[]): string {
  return [
    `# ${projectName} — Credits`,
    "",
    "Generated by Guildhall from the project roster. Everyone listed is a verified contributor.",
    "",
    "| Name | Role |",
    "|---|---|",
    ...rows.map((r) => `| ${r.name.replace(/\|/g, "")} (@${r.handle}) | ${r.role.replace(/\|/g, "")} |`),
    "",
  ].join("\n");
}
